research/existing-landscape.md
The original research incorrectly claimed that LaunchDarkly performed local evaluation in their SDKs.
=> fixed LaunchDarkly flag evaluation architecture

glossary.md
I'm not a fan of "Application Integrator" as a label, but couldn't think of a better term. Suggestions welcome!
=> Add Application Integrator to User Roles in glossary

glossary.md
As mentioned in the meeting, this avoids some overload and logical terminology clashes, both within OpenFeature (`hookContext.context`) and without, and I believe maps more specifically to the feature-flags use-case than "context".
Also added a blurb about intent to use implicit state storage mechanisms to propagate attributes.
=> Add details, "Context" to "Evaluation Context"

Makefile, README.md, specification/README.md, specification/design-principles.md, specification/evaluation-context/evaluation-context.md, specification/flag-evaluation/flag-evaluation.json, specification/flag-evaluation/flag-evaluation.md, specification/flag-evaluation/hooks.md, specification/glossary.md, specification/provider/providers.md, specification/types.md, tools/specification_parser/specification_parser.py, tools/specification_parser/specification_parser_test.py, tools/specification_parser/test_specification.json, tools/specification_parser/test_specification.md
First pass at a partial spec, based on cumulative findings from our [research repo](https://github.com/open-feature/sdk-research). Only the `Evaluation API` is proposed (`specification/flag-evaluation/flag-evaluation.md`, also note the associated assertion JSON file: `specification/flag-evaluation/flag-evaluation.json`). The best way to view the actual spec is probably to view the branch directly, since it's mostly markdown: https://github.com/open-feature/spec/tree/spec/flag-evaluation-api/specification
One of the goals was to design the structure of the spec, so I've included stubs for some of the other parts.
Please also checkout the `specification/README.md`, which contains an overview, conformance clause, and document statuses. 
For ease of generating the JSON assertion files, I've …
=> Add flag-evaluation spec, Makefile, initial spec structure

specification/flag-evaluation/flag-evaluation.json, specification/flag-evaluation/flag-evaluation.md, specification/glossary.md, specification/provider/providers.json, specification/provider/providers.md, specification/types.md
Added provider spec, with minor associated changes to the existing flag-evaluation spec file.
=> Add provider spec

Makefile, tools/specification_parser/lint_json_output.py
Example output:
```
❯ make lint
Non json-spec formatted file found: specification/flag-evaluation/something.json
specification/flag-evaluation/flag-evaluation.json: Rule 1.18 is missing a RFC 2119 keyword
specification/flag-evaluation/flag-evaluation.json: Rule 1.19 is missing a RFC 2119 keyword
Non json-spec formatted file found: specification/flag-evaluation/flag-evaluation.json
make: *** [lint] Error 2
```
=> Adds a linter.

.specignore, tools/specification_parser/specification_parser.py
When running the parser I was annoyed that some non-specification files had JSON files created, so I modified the parser to support a basic `.specignore` file which is just a line-separated list of UNIX style globs.
Also cleaned up some unused and duplicate imports in the parser
=> parser: add support for .specignore file

.github/workflows/json-changed.yaml
This ensures that the markdown and JSON files can never be out of sync.
=> Add a github actions workflow to ensure JSON files are up to date

.github/workflows/pr-checks.yaml, Makefile, specification/README.md, specification/evaluation-context/evaluation-context.json, specification/evaluation-context/evaluation-context.md, specification/flag-evaluation/flag-evaluation.json, specification/flag-evaluation/flag-evaluation.md, specification/glossary.md, specification/provider/providers.md, specification/types.md
First pass at evaluation context.
Lot's of questions here. I opted not to leverage something like the [elastic common schema](https://www.elastic.co/guide/en/ecs/current/ecs-client.html) for now, I believe it might be overkill. I used it, as well as [OIDCs standard claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) only as inspiration.
=> Add evaluation context spec

.markdownlint.yml, .prettierrc.yaml, specification.json, specification/evaluation-context/evaluation-context.md, specification/flag-evaluation/flag-evaluation.md, specification/flag-evaluation/hooks.md, specification/glossary.md, specification/provider/providers.md, specification/types.md, tools/specification_parser/lint_json_output.py
This spec has 2 commits, I strongly suggest you look at them one at a time, since the second is purely whitespace changes.
1st commit:
- breaks the flag-evaluation.md doc into sections, more like the hooks.md doc, to prevent so much number thrashing in the future
- improves consistency of terminology across files (see comments)
- specifies that both `error` and `finally` user-defined hooks may throw. This may be controversial, but I think it makes sense (and finally can already throw, as per spec). User-defined code being able to throw seems like a plus too me. See comments.
2nd commit: 
- sets `proseWrap: never` in prettier. This improves readability in PRs. As it stands, the fact that line-wrapping is on adds a lot of unneeded deltas in commits, since adding a new word might totally …
=> Language & number consistency

specification.json, specification/flag-evaluation/flag-evaluation.md, specification/glossary.md
- Updates `error code` definition to clearly be a free form string (as we've discussed previously, and as indicated by the [types specification](https://github.com/open-feature/spec/blob/main/specification/types.md#resolution-details), and adds some examples.
- Adds `targeting key` and `flag key` to glossary.
Fixes: https://github.com/open-feature/spec/issues/82
Fixes: https://github.com/open-feature/spec/issues/50
=> Add glossary terms, update errors/examples

specification.json, specification/flag-evaluation/flag-evaluation.md
See title, based on discussion here: https://github.com/open-feature/spec/issues/44
Closes: https://github.com/open-feature/spec/issues/44
=> Client creation must not throw

README.md, specification/README.md, specification/design-principles.md
A lot of whitespace/line break changes here. The only actual change is the `Design Principles` section, and removing the link to the "Design Principles" stub.
=> Remove design-principles stub, update

specification.json, specification/flag-evaluation.md
See https://github.com/open-feature/spec/issues/115 for the context.
Discussion also on [slack](https://cloud-native.slack.com/archives/C0344AANLA1/p1658587751496079).
=> Have different methods for float and int

.markdownlint.yml, Makefile, specification/README.md, specification/glossary.md, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md, specification/sections/03-evaluation-context.md, specification/sections/04-hooks.md, specification/sections/_category_.json, specification/types.md
At the last community meeting, we talked about including the spec in our documentation. This can be done with a git submodule and copying over the files as a prebuild step in Docusaurus. In preparation for that, I've updated the structure of the spec and included additional metadata. No changes to the spec itself were made.
Here is are a few examples of what it looks like in the docs.
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>
=> restructure spec and include metadata for docs

specification.json, specification/sections/03-evaluation-context.md
Adding a section about merging context. This is already partially done in the [node-sdk](https://github.com/open-feature/node-sdk/blob/8157870ba7c3a9913b4d9f8ac14f113057e8b8db/src/open-feature.ts#L57) and [dotnet-sdk](https://github.com/open-feature/dotnet-sdk/blob/0146a5e1500d37ed0cf3366133281c3632728f1c/src/OpenFeature/OpenFeature.cs#L84), and there's a comment about it in the [java-sdk](https://github.com/open-feature/java-sdk/blob/1b6314402ba080e1e302357b6fb740bb3beca762/src/main/java/dev/openfeature/javasdk/OpenFeatureClient.java#L41).
For this reason I think this is a fairly minor and even predicted change so I haven't created an OFEP... but let me know if you think this is a big deal:tm:
=> Merging context

specification.json, specification/sections/03-evaluation-context.md
Following the discussion [here](https://cloud-native.slack.com/archives/C0344AANLA1/p1659469589273419) and this [issue](https://github.com/open-feature/java-sdk/issues/40), I believe it is necessary to explicitly say that each key from the `EvaluationContext` should be unique.
=> EvaluationContext each key should be unique

specification.json, specification/sections/02-providers.md, specification/sections/04-hooks.md
refs https://github.com/open-feature/research/pull/22
=> Remove context transformers. Add provider hooks

specification.json, specification/sections/04-hooks.md
=> Document context merging order for before hook ctx

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md
- remove entire `context transformation` section (has not been widely adopted)
- remove mention `context transformation` from provider hooks
- add a bit more context to provider hooks intro
See: https://github.com/open-feature/spec/pull/119#issuecomment-1209128006
cc @agentgonzo @justinabrahms @beeme1mr
=> Remove context transformation, ref in provider hooks

specification.json, specification/sections/02-providers.md
BREAKING CHANGE
https://github.com/open-feature/spec/issues/133
=> Removed EvaluationOptions from FeatureProvider method signatures

specification.json, specification/sections/02-providers.md, specification/types.md
~Many SDKs have implemented these reasons as enums or limited strings, they are not free-form. I also think we can be reasonably confident most evaluation reasons can be bucketed into one of these.~
~This PR:~
- ~adds the `reasons` previously in a non-normative section into a normative section~
- ~adds a table explaining each reason~
~If we think that reasons should be free-form, we should make changes in SDKs to support this. If you think a reason is missing, feel free to add it or make a case in a comment.~
:warning: UPDATE: I've updated this PR. I think the consensus is to have an extensible set pre-defined strings for `Reasons`. See the thread for more reasoning, but TLDR:
- we don't expect developers to write logic around `Reaons`; they are for logging/debugging/telemetry
- most …
=> add reasons, table

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md, specification/types.md
See https://github.com/open-feature/spec/issues/141 for context.
=> feat!: make error code an enum and include optional error message

specification/README.md
Adds document statuses explaining stability of various spec documents and sub-sections.
This is important as we move toward's 1.0 SDK releases and a stable spec.
=> chore: add additional document statuses

README.md, specification.json, specification/README.md, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md, specification/sections/03-evaluation-context.md, specification/sections/04-hooks.md
**Marking Evaluation API and Providers `hardening`** and a few non-functional changes here that improve structure. 
specifically:
- explicitly mark and number all sections
- section headings have consistent numbering  (provider section numbering was different than the other docs)
- removed "draft" language 
An alternative to marking all of `provider` and `evaluation API` as hardening would be just marking all existing sections therein as hardening, which might be better since we'd have to do that anyway if we added a new experimental section.
see: https://github.com/open-feature/spec/issues/146 for more on release goals.
=> chore: section clarity, harden API, providers

specification/types.md
A small change to make the timezone info on the `Datetime` type optional. Some SDKs already do not include timezone info.
Since it's loosening this definition, this is non-breaking.
=> chore: clarify timezone requirement

specification.json, specification/sections/02-providers.md
Evaluation details and flag evaluation names usages for resolution details type were fixed.
Signed-off-by: Nikita Bishonen <git@bshn.rs>
In documentation regarding Provider different names were used instead of `resolution details`. This PR removes wrong or out of date names.
=> Fix usage of wrong type instead of resolution details

.gitignore, specification.json, specification/sections/02-providers.md, specification/types.md
Revives the `STATIC` reason in order to determine which values are cacheable.
Introduces the CACHED reason in order to report to the client that the value has been retrieved from cache.
Fixes #165
=> docs: include STATIC and CACHED in provider reasons

Makefile, specification/glossary.md, specification/sections/02-providers.md, specification/types.md
We we're missing some checks for `markdown-link-check`.
Unfortunately, there's some bugs in it that don't check anchors in other docs, so until that's fixed we might still occasionally get broken links. I've manually fixed all link issues with this PR though (I hope).
There doesn't appear to be many alternatives, so we may want to consider fixing [this bug](https://github.com/tcort/markdown-link-check/issues/212).
=> fix: links and link checks

specification.json, specification/sections/01-flag-evaluation.md
Adds support for mapping a named client to a specific provider.
Refs https://github.com/open-feature/ofep/pull/56
Example of this implemented in Java: https://github.com/open-feature/java-sdk/pull/388
=> Spec change for named client -> provider mappings

specification/glossary.md
Refs: https://github.com/open-feature/java-sdk/pull/388
=> chore: add client mapping info to glossary

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md, specification/sections/03-evaluation-context.md, specification/types.md, tools/specification_parser/specification_parser.py, tools/specification_parser/test_specification.md
Adds initialization and shutdown discussed in DRAFT client PR, and OFEPs. This is a piece of the (too big) draft PR [here](https://github.com/open-feature/spec/pull/171). The changes are fairly small and non-breaking.
There's a few non-functional changes here (fixes to formatting and minor enhancements to the parser).
Be sure to review `specification.json` for the net changes.
Most of this is implemented in the [web-sdk](https://github.com/open-feature/js-sdk/tree/main/packages/client/src) already. Some conforming (demo) providers can be found in the playground:
- [cloudbees](https://github.com/open-feature/playground/blob/main/packages/web-cloudbees-provider/src/lib/web-cloudbees-provider.ts)
- [flagsmith](https://github.com/open-feature/playground/blob/main/packages/web-flagsmith-provide …
=> feat: initialization and shutdown

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md
* loosen shutdown requirements to support things like go ctx https://github.com/open-feature/spec/issues/189
* clarify how to handle init/shutdown of providers bound to multiple names https://github.com/open-feature/spec/issues/192
* ~clarify init function should terminate before provider used https://github.com/open-feature/java-sdk/pull/456#discussion_r1210725372~
* clarify that authors can await the READY event during init https://github.com/open-feature/java-sdk/pull/456#discussion_r1210725372
cc @open-feature/technical-steering-committee @lopitz @lukas-reining @kinyoklion @Kavindu-Dodan 
Definitely let me know anyone thinks something is missing or could be improved here.
=> fix: various clarifications

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/05-events.md, specification/types.md
* Adds additional clarity regarding provider/client name mapping, as well as intent
* Replaces client-name for provider-name in events-details
* adds "STALE" state
* handlers for ANY state run immediately if provider is in that state
The only functional changes here are small ones related to events, and a new provider state, so particularly interested in @Kavindu-Dodan and @lukas-reining 's opinions on this one.
Relates to https://github.com/open-feature/spec/pull/200, which depends on `STALE` state.
=> feat: STALE state, run handlers for current state immediately, provider name

specification.json, specification/sections/01-flag-evaluation.md
Following this [OFEP](https://github.com/open-feature/ofep/blob/main/011-OFEP-sdk-wait-provider-ready.md) adding a **SHOULD** to the spec to have a blocking `setProvider`.
=> feat: blocking setProvider

.markdownlint.yml, specification/README.md, specification/sections/01-flag-evaluation.md, specification/sections/03-evaluation-context.md, specification/types.md
Opened based on [this](https://cloud-native.slack.com/archives/C0344AANLA1/p1695135349572539?thread_ts=1695111710.764429&cid=C0344AANLA1) slack thread.
* add details about evaluation details
* add note about advanced type usage
* convert all notes to proper markdown notes
=> chore: clarify eval details funcs/structs

specification.json, specification/sections/02-providers.md
Adds missing **STALE** state to provider state diagram. The STALE state was documented in the [Types](https://openfeature.dev/specification/types/#provider-status) section.
=> fix: add stale state to provider state diagram

specification/types.md
We made this change in the spec: https://openfeature.dev/specification/sections/events#requirement-523
But neglected to update it in "types"... it's already implemented in most SDKs.
=> fix: correct `event details` type, include `provider name`

specification.json, specification/sections/04-hooks.md
I neglected to add this qualifier when we released the updates for client (static-context). This requirement isn't relevant when the context is global and can only be changed via `OpenFeature.setContext`.
Thanks for the [find](https://github.com/open-feature/js-sdk/issues/630#issuecomment-1818743111), @lukas-reining .
=> fix: add dynamic-context condition to 4.1.4

specification.json, specification/sections/02-providers.md
Add requirement clarifying providers requiring initialization return to `NOT_READY` after shutdown, as agreed on [here](https://github.com/open-feature/spec/issues/213).
Fixes: https://github.com/open-feature/spec/issues/213
=> feat: NOT_READY after provider shutdown

specification/sections/04-hooks.md, specification/types.md
- addresses an invalid anchor
- removed parenthesis that causes a false positive in Docusaurus
There's a bug in the invalid link detection in Docusaurus 3 with no ETA on a fix. The PR works around the issue.
https://github.com/facebook/docusaurus/issues/9518
=> fix: invalid links detected by Docusaurus

specification.json, specification/sections/05-events.md, specification/types.md
This PR adds points to specify the behaviour of on context changed with respect to eventing.
- (optionally) emit `PROVIDER_STALE` when on context changed is executed with mismatching contexts
- emitting `PROVIDER_CONTEXT_CHANGED` when on context changed successfully terminates
- emitting `PROVIDER_ERROR` when on context changed terminates abnormally
=> feat: emit events on context change (client-only)

specification.json, specification/sections/01-flag-evaluation.md
This is a purely editorial change.
This is clearly about setting a provider, so I've moved it from the `Creating a client section` to the `Setting a provider` section.
=> chore: move 1.1.8 content to 1.1.2.4

.github/workflows/repo-stats.yaml
Adds repo stats to special `github-repo-stats` branch to overcome the 14-day limitation of GitHub's built-in traffic statistics.
=> chore: add repo stats

README.md
Improves the overall look and feel of the spec readme. This PR brings the readme more in line with other repos.
https://github.com/open-feature/spec/pull/232/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
=> docs: improve spec readme

specification.json, specification/glossary.md, specification/sections/01-flag-evaluation.md, specification/sections/03-evaluation-context.md, specification/sections/05-events.md
- defines `domain` as a concept
- updates references to client name to use `domain`
- add `domain` as client metadata
Fixes #228
- Update the readme template
- Update the openfeature.dev SDK compatibility table
=> feat: add domain as an openfeature concept

specification/types.md
Attempt to clarify the `reason` field of the resolution details.
Fixes #236
=> chore: Clarify resolution detail reason.

specification.json, specification/sections/01-flag-evaluation.md
Improving the language neutrality of this section (we usually use "abnormally terminate" not "throw", since many langs don't have "throw" semantics).
=> fix: language-neutral verbiage for set-and-wait

specification.json, specification/glossary.md, specification/sections/03-evaluation-context.md
Adds context propagation as described in #81.
To me it looks like this should be implementable in all the current languages.
The following things I am not sure on: 
- Is this concrete enough?
- Should 3.2 and 3.3 be switched around as 3.3 is assumed in 3.2?
- Should we nest the requirements more e.g. do we want to have a specific section for the propagator?
Fixes #81
=> feat: context propagation

specification.json, specification/sections/02-providers.md
Adds callout for language-specific `initialize` function naming. This is an idea @toddbaert had in [this review](https://github.com/open-feature/ruby-sdk/pull/78#discussion_r1480335799).
=> docs: add language-specific initialize naming

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md, specification/sections/03-evaluation-context.md, specification/sections/05-events.md, specification/types.md
* moves provider state into SDK (SDK now maintains provider state/lifecycle; provider interface is now "stateless")
* refine semantics around client state when context is pending/reconciled by using new events/states, instead of STALE
* add PROVIDER_FATAL error code
Resolves: https://github.com/open-feature/spec/issues/238
--- 
For background discussion, see https://github.com/open-feature/spec/issues/238
---
This should make provider authorship less error prone, and simpler. Providers essentially become stateless as far as the SDK is concerned. The provider is only obligated to optionally implement the `initialize`, `shutdown` and `onContextChange` functions and maintain is own private state (caches, connection, etc).
This also refines the semantics around context reconciliation, which …
=> feat: internal provider state, new client events

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/05-events.md, specification/types.md
No substantial changes here, just editorial improvements and corrections.
When implementing https://github.com/open-feature/spec/pull/241, I noticed a few oversights (see comments).
=> fix: minor corrections around FATAL state

specification/types.md
Requirement 5.1.5 speaks of a Provider Event Details `error code` field but this field was missing from the specified type. 
This field is required to then populate the Event Details `error code` field.
=> fix: add missing Provider Event Details 'error code' field

specification/glossary.md, specification/sections/05-events.md
Adding some additional non-normative text to clarify a few things at the prompt of @federicobond .
The meaning and justification should be self-evident, and if it's not I did a bad job. :sweat_smile:
=> chore: clarify event/domain scoping, lifecycle

specification/types.md
In section 4.5.1 of hooks it specifies:
```
> `Flag evaluation options` **MAY** contain `hook hints`, a map of data to be provided to hook invocations.
```
But it does not include this in the types.md file, which makes this a bit confusing.
=> fix: Include hook hints in evaluation options type.

specification/sections/01-flag-evaluation.md
This causes an error in the website, it should be JSX.
=> fix: use jsx syntax for legend color

specification/README.md, specification/sections/01-flag-evaluation.md, specification/sections/03-evaluation-context.md, specification/types.md
- adds hard new lines to GitHub notes
GitHub does some magic behind the scenes that isn't part of the markdown standard. This causes some issues on our doc site. Explicitly adding a hard line break using double space helps us avoid this issue.
Update the docs to include this change.
=> Add hard line breaks to GitHub notes

tools/repo_parser/Dockerfile, tools/repo_parser/README.md, tools/repo_parser/spec_finder.py
```
$ docker build -t specfinder .
$ docker run --mount src=/path/tojava-sdk/,target=/appdir,type=bind -it specfinder \
spec_finder.py --code-directory /appdir --diff --json-report
```
This will generate `java-report.json` in the java-sdk folder which we can use for other automation.
The report looks like this:
```json
{
"extra": [
"1.1.8",
"2.4.2",
"2.4.3",
"2.4.4",
"2.4.5",
"4.1.4"
],
"missing": [
"1.1.2.4",
"1.7.1",
"1.7.2.1",
"1.7.3",
"1.7.4",
"1.7.5",
"1.7.6",
"1.7.7",
"1.7.8",
"2.4.2.1",
"2.5.2",
"3.2.2.3",
"3.2.2.4",
"3.2.4.2",
"4.1.4.1",
"5.1.5",
"5.3.4.1",
"5.3.4.2",
"5.3.4.3",
"5.3.5"
],
"different-text": [
"1.1.3",
"1.1.6",
"1.2.2",
"2.4.1",
"2.6.1",
"3.2.3",
"3.2.4.1"
],
"good": [
"1.1.1",
"1.1.2.1",
"1.1.2.2",
"1.1.2.3",
"1.1.4",
"1.1.5",
"1.1.7",
"1.2.1",
"1.3.1.1", …
```
=> chore: An image for parsing repo spec compliance.

tools/repo_parser/requirements.txt, tools/repo_parser/spec_finder.py, tools/repo_parser/test_spec_finder.py
This should allow someone to mark specifications as done based on inline comments, rather than having to hand-roll regexes.
set this in your `.specrc` (example is for go)
```cfg
[spec]
file_extension=go
inline_comment_prefix=//
```
then edit code by adding lines like:
```
import (
"errors"
"fmt"
"sync"
"github.com/go-logr/logr"
"github.com/open-feature/go-sdk/openfeature/internal"
"golang.org/x/exp/maps"
)
//  spec:5.3.5:If the provider emits an event, the value of the client's provider status MUST be updated accordingly.:end
// spec:5.3.4.3:If the provider's on context changed function terminates
// abnormally, and no other invocations have yet to terminate, associated
// PROVIDER_ERROR handlers MUST run.:end
// evaluationAPI wraps OpenFeature evaluation API functionalities
type …
```
=> feat: Inline comment support for spec repos

specification/sections/06-tracking.md
- Adds section 6: tracking
- no normative sections
- overview
- goals/non-goals (temporary)
This is not final! Please review goals/non-goals especially, and add any questions you might have.
=> feat: tracking

specification.json, specification/appendix-a-included-utilities.md, specification/sections/01-flag-evaluation.md
As discussed in recent meetings, we've had complaints about this from multiple sources. This PR adds a stipulation that no logging is done by the SDK during flag evaluation. It also defines a very simple `logging hook` concept as an included utility. These should be very simple to write and will provide all the needed logging but give authors more control than built in log statements. It will also be a very nice intro to the hooks concept for users.
Here's the Java implementation: https://github.com/open-feature/java-sdk/pull/1084
=> feat: logging requirements and logging hook

specification/appendix-a-included-utilities.md
Minor clarifications to the in-memory provider, especially around `flags changed` which at the moment is not consistently implemented.
=> fix: clarify in-memory provider reqs

specification/sections/01-flag-evaluation.md
The mermaid diagram for `Provider lifecycle` has few arrows with `Unsupported markdown: list` text. It will be fixed by using `#ast`;
https://mermaid.js.org/syntax/flowchart.html#entity-codes-to-escape-characters
=> chore: use html entity code for asterisk in mermaid diagram

specification.json, specification/sections/04-hooks.md
- extends the `finally` stage in hooks to include evaluation details.
#281 
This is a breaking change but will significantly enhance the usefulness of the `finally` stage. Currently, the `finally` stage is used to perform end-of-transaction or clean-up tasks. If this proposal is accepted, the `finally` stage will have access to the same evaluation details that are returned to the application author.
This change will make implementing the OpenTelemetry Feature Flag Semantic Convention changes easier because the evaluation details in the `finally` stage can contain all the telemetry we'll need. Values like `flag set id` and `flag set version` can be supplied via flag metadata, which isn't accessible in the `error` or current `finally` stages.
Here's a [draft …
=> feat!: add evaluation details to finally hook

specification/assets/gherkin/metadata.feature
Adds gherkin test to verify that flag evaluations provide metadata
Part of #1467 ([https://github.com/open-feature/flagd/issues/1467](https://github.com/open-feature/flagd/issues/1467))
Implement steps of the gherkin file in the repositories, and add test data according to the issue
=> feat: Update test harness with metadata assertions #1467

specification/assets/gherkin/evaluation.feature, specification/assets/gherkin/hooks.feature
Adds gherkin tests to verify the evaluation details passed to the finally hooks
Part of [https://github.com/open-feature/.github/issues/65](https://github.com/open-feature/.github/issues/65), [https://github.com/open-feature/php-sdk/issues/140](https://github.com/open-feature/php-sdk/issues/140), [https://github.com/open-feature/python-sdk/issues/403](https://github.com/open-feature/python-sdk/issues/403), [https://github.com/open-feature/dotnet-sdk/issues/328](https://github.com/open-feature/dotnet-sdk/issues/328), [https://github.com/open-feature/java-sdk/issues/1246](https://github.com/open-feature/java-sdk/issues/1246), and [https://github.com/open-feature/js-sdk/issues/1109](https://github.com/open-feature/js-sdk/issues/1109)
Implement the test steps in the repos
=> Add gherkin tests to verify evaluation details in finally hooks

specification/assets/gherkin/hooks.feature
Passing a default value with incorrect type is not enough to trigger a `TYPE_MISMATCH` error. This PR changes the test such that an existing flag of type string is requested, but the test requests it as a boolean flag
=> noissue: fix the test hook behaviour on type error

specification/assets/gherkin/contextMerging.feature
Adds gherkin tests to verify the merging order of contexts: https://openfeature.dev/specification/sections/evaluation-context/#requirement-323
See https://github.com/open-feature/flagd-testbed/issues/13
=> feat: Add new test suite for context merging

specification/assets/gherkin/contextMerging.feature
This pull request includes updates to the `specification/assets/gherkin/contextMerging.feature` file to improve the clarity of scenario descriptions by specifying the context (transaction, hook, or both) in which the context entries are added or overwritten.
Changes to scenario descriptions:
* Updated the scenario description to specify that the context entry is added for a transaction.
* Updated the scenario description to specify that the context entry is added for a hook.
* Updated the scenario description to specify that the context entry is added for both a transaction and a hook.
* Updated the scenario outline description to specify that the context entry overwrites values for a transaction.
* Updated the scenario outline description to specify that the context entry overwrites …
=> fix: Clarify scenario descriptions in context merging feature

specification/sections/02-providers.md
just fixes the java syntax in the providers tracking code example
=> fix(docs): change tracking code example to use proper java syntax

specification.json, specification/sections/04-hooks.md
Loosens the value definition for hook data.
In the example within the spec, and within the implementation in the dotnet-sdk, the intent was to allow any type of data. For example creating an open telemetry span in before, storing it hook data, and ending it in after.
Related to: https://github.com/open-feature/dotnet-sdk/pull/387
=> fix: Broaden definition of hook data value types.

specification/appendix-d-observability.md
- update the observability appendix to include the latest otel semcon
Marking as a draft until we find out if `value` can be moved out from the `body`.
https://docs.google.com/document/d/1x9hprUaUNlVCZMtFAqBcj6h50ukpT0hCAli7BzgWsTQ/edit?tab=t.0
=> feat!: update the observability appendix to include the latest otel semcon

CODEOWNERS
This will add the technical steering committee members to new spec PRs.
=> Add a codeowner, set TSC as the spec owner.

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md
This is a minor point of clarification with no material changes.
When we removed `status` from the providers, we didn't migrate this point to the evaluation API, as @fabriziodemaria pointed out [here](https://github.com/open-feature/spec/issues/270).
Fixes: https://github.com/open-feature/spec/issues/270
=> fix: correct shutdown points after status removal

specification/appendix-a-included-utilities.md
This PR updates the Multi-Provider documentation in the OpenFeature specification to document the new `track` method support that was added in [PR #1323](https://github.com/open-feature/js-sdk-contrib/pull/1323).
- **Track Method Support**: Added a section explaining how the Multi-Provider implements tracking functionality
- **Introduction Section**: Updated use case examples to highlight tracking capabilities
- **BaseEvaluationStrategy**: Added `shouldTrackWithThisProvider` method to the abstract class
```typescript
// Basic tracking usage
const multiProvider = new MultiProvider([
{ provider: new ProviderA() },
{ provider: new ProviderB() }
])
await OpenFeature.setProviderAndWait(multiProvider)
const client = OpenFeature.getClient()
// Track events across all ready providers …
```
=> docs(multi-provider): Document Track Method Support in Multi-Provider

specification.json, specification/sections/01-flag-evaluation.md, specification/sections/02-providers.md
This is a change that I suspect will have little practical impact for most users, but helps disambiguate some behavior that recently caused [issues](https://github.com/open-feature/go-sdk/issues/397) and [confusion](https://github.com/open-feature/go-sdk/pull/400/files#r2191214490).
This is only one means of addressing this concern, so please don't hesitate to put forward alternative proposals.
"Idempotent" may not be exactly the right word here, since it's only idempotent within the scope of one execution of the life-cycle, so I'm open to copy changes here as well.
:warning: I've substantially changed this PR based on feedback, and dismissed all approvals:
As @erka and others have pointed out, practically, `shutdown` has been used for more than just cleaning up providers, it's also used …
=> feat: add point 1.6.2, 2.5.3 about shutdown details

specification/sections/04-hooks.md
- clarify evaluation context in hook requirements
Fixes #328
I added the clarification in the non-normative section. Hopefully, this addresses the ambiguity around what we mean by `evaluation context`.
=> docs: clarify evaluation context in hook requirements
